spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Fireny6208!


  jpa: # JPA관련 설정
    database: mysql       # 사용하는 데이터 베이스
    show-sql: true        # 콘솔창에 SQL문을 띄워줄건지
    hibernate:
      ddl-auto: create    # hibernate 적용 전략
    properties:
      hibernate:
        format_sql: true  # hibernate sql문을 가독성 있게 보여줌 (ex. 줄바꿈 문자)


logging:
  level:
    org.hibernate.SQL: debug